- name: Create directories for kube state metrics
  ansible.builtin.file:
    path: kube_state_metrics
    state: directory
    mode: 0700

- name: Apply Kube-State-Metrics deployment
  template:
    src: kube-state-metrics.yaml.j2
    dest: kube_state_metrics/kube-state-metrics-deployment.yaml

- name: Apply Kube-State-Metrics YAML to the cluster
  shell: kubectl apply -f kube_state_metrics/kube-state-metrics-deployment.yaml
