- name: Create directories for node cadvisor
  ansible.builtin.file:
    path: cadvisor
    state: directory
    mode: 0700

- name: Apply cAdvisor deployment
  template:
    src: cadvisor.yaml.j2
    dest: cadvisor/cadvisor-deployment.yaml

- name: Apply cAdvisor YAML to the cluster
  shell: kubectl apply -f cadvisor/cadvisor-deployment.yaml 
