---
# - name: HA Preparation
#   hosts: ha

#   roles:
#   - ha

- name: Deploy first master
  hosts: masters[0]

  roles:
  - k8s/create
  - k8s/auth

  post_tasks:
    - name: Wait for the node to be ready
      ansible.builtin.include_tasks: k8s-ready.yaml

# - name: Setup cluster monitoring
#   hosts: masters[0]
#   vars:
#     remote_write_address: "{{ k8s['cluster_monitoring']['prometheus']['remote_write_address'] }}"
#     remote_write_port: "{{ k8s['cluster_monitoring']['prometheus']['remote_write_port'] }}"
#     remote_write_user: "{{ k8s['cluster_monitoring']['prometheus']['remote_write_user'] }}"
#     remote_write_pass: "{{ secrets['prometheus_basic_auth_password'] }}"
#     remote_data_label: "{{ k8s['cluster_monitoring']['prometheus']['remote_data_label'] }}"
#     loki_address: "{{ k8s['cluster_monitoring']['promtail']['loki_address'] }}"
#     loki_port: "{{ k8s['cluster_monitoring']['promtail']['loki_port'] }}"
#     loki_label: "{{ k8s['cluster_monitoring']['promtail']['loki_label'] }}"

#   roles:
#   - cluster_monitoring

- name: Attach masters
  hosts: masters[1:]
  vars:
    token: "{{ hostvars['ansible_dummy_host']['_token'] }}"
    ca_cert_hash: "{{ hostvars['ansible_dummy_host']['_ca_cert_hash'] }}"
    certificate_key: "{{ hostvars['ansible_dummy_host']['_certificate_key'] }}"
    kube_config_local_path: "{{ hostvars['ansible_dummy_host']['_kube_config'] }}"
    master: "{{ k8s['apiserver_advertise_address'] }}"
    is_control_plane_node: true
  environment:
    PATH: '{{ansible_env.PATH }}:/usr/local/bin/'

  roles:
    - role: k8s/join
  post_tasks:
    - name: Wait for the node to be ready
      ansible.builtin.include_tasks: k8s-ready.yaml

- name: Install k8s nodes
  hosts: workers:!masters
  vars:
    token: "{{ hostvars['ansible_dummy_host']['_token'] }}"
    ca_cert_hash: "{{ hostvars['ansible_dummy_host']['_ca_cert_hash'] }}"
    kube_config_local_path: "{{ hostvars['ansible_dummy_host']['_kube_config'] }}"
    master: "{{ k8s['apiserver_advertise_address']"
  environment:
    PATH: '{{ansible_env.PATH }}:/usr/local/bin/'

  roles:
    - role: k8s/join
  post_tasks:
    - name: Wait for the node to be ready
      ansible.builtin.include_tasks: k8s-ready.yaml

# - name: Install metallb
#   hosts: masters[0]

#   roles:
#     - role: k8s/metallb
#       when: k8s.metallb is defined