- name: Deploy Core, RAN, and UE
  hosts: masters[0]
  gather_facts: yes

  roles:
  - role: 5g/base
  - role: 5g/core
    when: GCN.core.present | default(false)
  - role: 5g/flexric
    when: GCN.flexric.present | default(false)
  - role: 5g/ran
    when: GCN.RAN.present | default(false)
  - role: 5g/ue
    when: GCN.UE.present | default(false)
  - role: experiments/prepare
  - role: experiments/execute
