---
- block:                                                       # must to be root
  - block:
    - name: Unhold system packages before removal
      become: true
      ansible.builtin.command:
        cmd: "apt-mark unhold {{ item }}"
      with_items: "{{ packages.system_remove }}"
      ignore_errors: yes

    - name: Remove package (system)
      become: true
      ansible.builtin.package:
        allow_change_held_packages: yes
        name: "{{ item }}"
        state: absent
      with_items: "{{ packages.system_remove }}"
    when: packages.system_remove is defined and packages.system_remove | length > 0

  - block:
    - name: Remove package (Python)
      become: true
      ansible.builtin.pip:
        name: "{{item}}"
        break_system_packages: true
        state: absent
      with_items: "{{ packages.system_remove }}"
    when: packages.system_remove is defined and packages.system_remove | length > 0

  - block:                                                     # system packages
    - name: Gather package (system)
      ansible.builtin.package_facts:
        manager: auto

    ## OS specific
    - name: Update Package Cache (apt/Ubuntu/Debian)
      ansible.builtin.apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

    ## Generic installation
    - name: Install package (system)
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages.system }}"
    when: packages.system is defined and packages.system | length > 0

  - block:                                                     # python packages
    - name: Gather package (Python)
      community.general.pip_package_info:
        clients: [pip3, pip]
      register: installed_pip_packages

    - name: Install package (Python)
      ansible.builtin.pip:
        name: "{{item}}"
        break_system_packages: true
      with_items: "{{ packages.python }}"
    when: packages.python is defined and packages.python | length > 0
  become: yes
