---
- block:                                                          # must be root
  - name: Remove existing GPG key file to ensure it can be updated
    become: yes
    ansible.builtin.file:
      path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      state: absent

  - name: Download Kubernetes GPG key and place it in /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    become: yes
    ansible.builtin.shell:
      cmd: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{ _k8s_version }}/deb/Release.key | gpg --batch --yes --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      executable: /bin/bash
    args:
      creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

  - name: Create /etc/apt/sources.list.d/kubernetes.list file
    copy:
      content: |
        deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ _k8s_version }}/deb/ /
      dest: /etc/apt/sources.list.d/kubernetes.list

  - name: Install k8s tools
    include_role:
      name: packages
    vars:
      packages:
        apt_options: "--allow-change-held-packages -y"
        system_remove: "{{k8s_tools}}"
        system: "{{k8s_tools}}"

  - name: Install helm (1/2)
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      dest: /tmp/get_helm.sh
      mode: '0555'
  - name: Install helm (2/2)
    ansible.builtin.shell: "/tmp/get_helm.sh"
  become: true
