# Deploy the RAN
- name: Cleanup RAN blueprint namespace 
  kubernetes.core.k8s:
    name: '{{ GCN.RAN.namespace }}'
    api_version: v1
    kind: Namespace
    wait: yes
    state: absent
    wait_condition:
        type: Complete 
        status: "True"
  when: GCN.RAN.cleanup is defined and GCN.RAN.cleanup

- name: Create RAN blueprint namespace 
  kubernetes.core.k8s:
    name: '{{ GCN.RAN.namespace }}'
    api_version: v1
    kind: Namespace
    state: present

- name: Deploy gNB
  kubernetes.core.helm:
    name: oai-gnb
    chart_ref: ./oai-cn5g-fed/charts/oai-5g-ran/oai-gnb
    release_namespace: '{{ GCN.RAN.namespace }}'
    wait: true
    force: true
  when: not GCN.RAN.split.f1 and not GCN.RAN.split.e1

- block:
  - name: Deploy gNB-CU
    kubernetes.core.helm:
      name: "cu-{{ item }}"
      chart_ref: "./oai-cn5g-fed/charts/oai-5g-ran/oai-cu{{ item | string if item > 1 else '' }}"
      release_namespace: '{{ GCN.RAN.namespace }}'
      wait: true
      force: true
    loop: "{{ range(1, GCN.RAN.count_CU + 1) | list }}"
    when: GCN.RAN.split.f1 and not GCN.RAN.split.e1

  - block:
    - name: Deploy gNB-CU-cp
      kubernetes.core.helm:
        name: cucp
        chart_ref: ./oai-cn5g-fed/charts/oai-5g-ran/oai-cu-cp
        release_namespace: '{{ GCN.RAN.namespace }}'
        wait: true
        force: true
    - name: Deploy gNB-CU-up
      kubernetes.core.helm:
        name: cuup
        chart_ref: ./oai-cn5g-fed/charts/oai-5g-ran/oai-cu-up
        release_namespace: '{{ GCN.RAN.namespace }}'
        wait: true
        force: true
    when: GCN.RAN.split.f1 and GCN.RAN.split.e1

- name: Deploy gNB-DU with Helm
  kubernetes.core.helm:
    name: "du-{{ item }}"
    chart_ref: "./oai-cn5g-fed/charts/oai-5g-ran/oai-du{{ item | string if item > 1 else '' }}"
    release_namespace: "{{ GCN.RAN.namespace | default('default') }}"
    wait: true
    force: true
    set_values:
      - value: config.cuHost="{% if  GCN.RAN.du_to_cu_mapping[item - 1].cu == 1 %}oai-cu.{{ GCN.RAN.namespace }}.svc.cluster.local{% else %}oai-cu{{ GCN.RAN.du_to_cu_mapping[item - 1].cu }}.{{ GCN.RAN.namespace }}.svc.cluster.local{% endif %}"
  loop: "{{ range(1, GCN.RAN.count_DU + 1) | list }}"
  when: GCN.RAN.split.f1 or GCN.RAN.split.e1


