# Deploy the UE

- name: Cleanup UE blueprint namespace 
  kubernetes.core.k8s:
    name: '{{ GCN.UE.namespace }}'
    api_version: v1
    kind: Namespace
    wait: yes
    state: absent
    wait_condition:
        type: Complete 
        status: "True"
  when: GCN.UE.cleanup is defined and GCN.UE.cleanup

- name: Create UE blueprint namespace 
  kubernetes.core.k8s:
    name: '{{ GCN.UE.namespace }}'
    api_version: v1
    kind: Namespace
    state: present

- name: Deploy UEs
  kubernetes.core.helm:
    name: "nrue{{ item }}"
    chart_ref: "./oai-cn5g-fed/charts/oai-5g-ran/oai-nr-ue{{ item if item > 1 else '' }}"
    release_namespace: '{{ GCN.UE.namespace }}'
    wait: true
    force: true
  loop: "{{ range(1, GCN.UE.count + 1) | list }}"
  when: GCN.UE.count is defined
