apiVersion: v1
kind: Service
metadata:
  name: oai-ran
  labels:
    {{- include "oai-du.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: f1c
      port: 38472
      targetPort: 38472
      protocol: SCTP
    - name: f1u
      port: {{ .Values.config.f1duPort}}
      targetPort: {{ .Values.config.f1duPort}}
      protocol: UDP
    # - name: uu
    #   port: 4043
    #   targetPort: 4043
    #   protocol: TCP
  selector:
    {{- include "oai-du.selectorLabels" . | nindent 4 }}



### if you vant to set:
  # {{- if .Values.global }}{{ if not .Values.global.clusterIpServiceIpAllocation }}
  # clusterIP: None
  # {{- end }}{{ end }}
## so that the ue pings to the svc intead of directly to the pod ip 
## than you need to open the 4043 TCP port (see commented lines)